Role mapping
Quansight/conda-store pull request #496
Opened 2023-07-10 16:36 UTC by pierrotsmnrd

This PR aims at solving issue #491

2023-07-17 15:00 UTC, costrouc requested changes
Overall looks good to me @pierrotsmnrd. I will try and run the tests that are failing and see what it is.

2023-07-19 06:43 UTC, pierrotsmnrd commented on conda-store-server/conda_store_server/orm.py
> +    # arn e.g. <namespace>/<name> like `quansight-*/*` or `quansight-devops/*`
I have added a validation and added some tests for this : 
https://github.com/Quansight/conda-store/pull/496/commits/d31ceaad1ebdd417f504e1fb4c0b0f63a2b3d4a7

2023-07-19 06:51 UTC, pierrotsmnrd commented on conda-store-server/conda_store_server/alembic/versions/b387747ca9b7_role_mapping.py
> +        "namespace", sa.Column("role_mapping_metadata", sa.JSON(), nullable=True)
`metadata_` works. `meta_data` as well. or anything like `extra_data`, `external_data`, `custom_data`

2023-07-19 07:11 UTC, pierrotsmnrd commented on conda-store-server/conda_store_server/server/auth.py
> +        db_role_mappings = {}
Haha yes, you're right. Some habits/patterns are hard to get rid of :) Done.

2023-07-19 19:49 UTC, costrouc approved these changes

2023-07-19 19:50 UTC, merged